version: "3.9"
services:

  database-server:
    image: postgres:16-alpine
    container_name: db
    restart: always
    volumes:
      - ./.pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database_name
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=...replace.password...
      - TZ=Europe/London
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
    ports:
      - "127.0.0.1:5432:5432"
